-- (1)
-- SELECT INS.ANIMAL_ID, INS.NAME
-- FROM ANIMAL_INS INS
-- WHERE INS.DATETIME > (SELECT OUTS.DATETIME FROM ANIMAL_OUTS OUTS WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID)
-- ORDER BY INS.DATETIME

-- (2)
-- SELECT INS.ANIMAL_ID, INS.NAME
-- FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
-- WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID AND INS.DATETIME > OUTS.DATETIME
-- ORDER BY INS.DATETIME

-- (3)
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME