-- (1)
-- SELECT INS.ANIMAL_ID, INS.NAME
-- FROM ANIMAL_INS INS
-- JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
-- ORDER BY (OUTS.DATETIME - INS.DATETIME) DESC
-- LIMIT 2

--(2)
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(SECOND, INS.DATETIME, OUTS.DATETIME) DESC
LIMIT 2